### ISSUE TITLE
push 1.0.0 to hex

### ISSUE THREAD

**Issue by nbw** [alexiob/scenic_driver_waveshare#1]
Hi there! cool project. I'm trying out the library now. Just so you know, only 0.8.1 is pushed to hex.pm.

For those seeings this message, the following in your deps should do the trick:

```elixir
      {:scenic_driver_waveshare, github: "alexiob/scenic_driver_waveshare"},
```

**Comment by alexiob** [comment]
@nbw thank you! And thank you for pointing out the issue: it is the README version that's actually wrong :)

Fixed and published 0.8.3.
